# Generated by Django 3.2.8 on 2021-10-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgcore', '0002_item_is_equippable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.ManyToManyField(blank=True, to='rpgcore.ItemProperty')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemSpecialProperties',
        ),
        migrations.RemoveField(
            model_name='item',
            name='charge_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='item',
            name='does_recharge',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_ranged',
        ),
        migrations.RemoveField(
            model_name='item',
            name='recharge_time',
        ),
        migrations.AlterField(
            model_name='item',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpgcore.item'),
        ),
        migrations.DeleteModel(
            name='ItemSubtype',
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='special_properties',
            field=models.ManyToManyField(blank=True, to='rpgcore.ItemSpecialProperty'),
        ),
    ]
