# Generated by Django 3.2.8 on 2021-10-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgcore', '0004_alter_item_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpgcore.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
