# Generated by Django 3.2.8 on 2021-10-14 14:32

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('rpgcore', '0005_auto_20211014_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
    ]
